# Config file for automatic testing at travis-ci.org

os: linux
dist: focal
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
addons:
  apt:
    packages:
      - x11-utils
      - libxkbcommon-x11-0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-xinerama0
      - libxcb-xfixes0
      - libpulse-mainloop-glib0
      - libgstreamer1.0-0
      - gstreamer1.0-tools
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-alsa
      - gstreamer1.0-libav
      - libxvidcore4
      - qt5-image-formats-plugins
      - bluez
      - python3-pyqt5
      - python3-pyqt5.qtwebengine
      # - libspeechd-dev
      # - libspeechd2
      - speech-dispatcher-espeak-ng
      - flite
      - libflite1
      - libqt5texttospeech5
      - libqt5bluetooth5
      - libqt5svg5
      - pulseaudio
      - qtspeech5-flite-plugin
      - speech-dispatcher
      - speech-dispatcher-flite

services:
  - xvfb
  # - speech-dispatcher
env:
  global:
    - QT_DEBUG_PLUGINS=1

before_install:
  - systemctl --user start pulseaudio.service
  # - systemctl --user enable bluetooth.service
  # - systemctl --user start bluetooth.service
  - speech-dispatcher -d
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install poetry --pre
  - poetry install -E pyqt5

# Command to run tests, e.g. python setup.py test
script:
  # - tox
  - poetry run pytest --doctest-modules --cov=prettyqt

after_success:
  - poetry run codecov
  - poetry config pypi-token.pypi $PYPI_TOKEN
  - make docs

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password

deploy:
  - provider: pages
    edge: true
    cleanup: false
    strategy: git
    local_dir: site
    token: $GITHUB_TOKEN
    keep_history: true
    on:
      tags: true
      repo: phil65/PrettyQt
      python: 3.7
  - provider: script
    edge: true
    script: poetry publish --build
    cleanup: false
    on:
      tags: true
      repo: phil65/PrettyQt
      python: 3.7
