# Config file for automatic testing at travis-ci.org

os: linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
      - x11-utils
      - libxkbcommon-x11-0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-xinerama0
      - libxcb-xfixes0
      - python3-pyqt5
      - python3-pyqt5.qtwebengine
services: xvfb
env:
  global:
    - QT_DEBUG_PLUGINS=1
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -E pyqt5

# Command to run tests, e.g. python setup.py test
script:
  # - tox
  - poetry run pytest --doctest-modules --cov=prettyqt

after_success:
  - poetry run codecov
  - poetry config pypi-token.pypi $PYPI_TOKEN
  - make docs

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password

deploy:
  - provider: pages
    edge: true
    cleanup: false
    strategy: git
    local_dir: site
    token: $GITHUB_TOKEN
    keep_history: true
    on:
      tags: true
      repo: phil65/PrettyQt
      python: 3.7
  - provider: script
    edge: true
    script: poetry publish --build
    cleanup: false
    on:
      tags: true
      repo: phil65/PrettyQt
      python: 3.7
