site_name: PrettyQt
site_url: https://readthedocs.org/projects/prettyqt/
nav:
    - Home: index.md
    - API:
        - api.md
        - core: api/core.md
        - gui: api/gui.md
        - widgets: api/widgets.md

theme:
    name: material
    custom_dir: theme_customizations/
plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            rendering:
              show_source: true

markdown_extensions:
    # - smarty
    - codehilite
    - admonition
    - pymdownx.superfences
    # - pymdownx.betterem
    # - markdown.extensions.footnotes
    # - markdown.extensions.attr_list
    # - markdown.extensions.def_list
    # - markdown.extensions.tables
    # - markdown.extensions.abbr
    # - markdown.extensions.md_in_html
use_directory_urls: false
