name: Python package

on: [push]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.platform }}
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: tlambert03/setup-qt-libs@v1
    - name: Linux opengl
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libopengl0 libegl1-mesa libxcb-xinput0
    # - name: start TextToSpeech service
    #   if: runner.os == 'Linux'
    #   run: |
    #     sudo apt-get install speech-dispatcher espeak
    #     speech-dispatcher -d
    # - name: Python Poetry Action
    #   uses: abatilo/actions-poetry@v2.1.0
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Test with pytest  (PyQt6)
      # combine test coverage with --cov-append?
      uses: coactions/setup-xvfb@v1
      timeout-minutes: 5
      with:
        run: |
          poetry install -E pyqt6
          poetry run pytest
    - name: Test with pytest (PySide6)
      uses: coactions/setup-xvfb@v1
      if: runner.os == 'Linux'
      timeout-minutes: 5
      with:
        run: |
          poetry install -E pyside6
          poetry run pytest --doctest-modules --junitxml=junit/test-results.xml --cov=prettyqt --cov-report=xml --cov-report=html

    - name: Upload coverage to Codecov
      if: runner.os == 'Linux' && matrix.python-version == '3.10'
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Create documentation
      # if: matrix.python-version == '3.10' && runner.os == 'Linux'
      run: |
        poetry install -E pyside6
        poetry run mkdocs build
    # - name: Build and publish
    #   if: startsWith(github.ref, 'refs/tags/v') && matrix.python-version == '3.10' && runner.os == 'Linux'
    #   run: |
    #     poetry config pypi-token.pypi ${{ secrets.PYPI_SECRET }}
    #     poetry publish --build
    # - name: Deploy docs
    #   if: startsWith(github.ref, 'refs/tags/v') && matrix.python-version == '3.10' && runner.os == 'Linux'
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./site

  deploy:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install packages
      # if: runner.os == 'Linux'
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry install -E pyside6
        poetry run mkdocs build
    - name: Build and publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_SECRET }}
        poetry publish --build
    # - name: Deploy docs
    #   # if: github.event_name == 'push'
    #   uses: mhausenblas/mkdocs-deploy-gh-pages@master
    #   # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     # CUSTOM_DOMAIN: optionaldomain.com
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
